package Presentacion;

//import Datos.AdministradorArrays;
import Datos.AdministradorArrays;
import Logica.Cliente;
import Logica.Texto;
import Logica.Vehiculo;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author Manuel
 */
public class IngresoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresoCliente
     */
    AdministradorArrays administradorArray;
    Cliente nuevo;
    static ArrayList<Cliente> listaClientes;

    public IngresoCliente() {
        initComponents();

        administradorArray = new AdministradorArrays();
        administradorArray.crearArrayList();

        Cliente.initClientes();
        listaClientes = Cliente.getClientes();

        // ArrayList<Cliente> llenarCboClientes =
        // administradorArray.llenarCboClientes();
        this.setSize(new Dimension(850, 450));
        this.setMinimumSize(new Dimension(200, 200));
        // cboClientes.setSelectedItem(administradorArray.retornaInformacionCliente());
    }

    // public void llenarCboClientes() {
    // ArrayList<String> lista = new ArrayList<>();
    // fvehiculo func = new fvehiculo();
    // lista = administradorArray.llenarCboClientes();

    // for (int i = 0; i < lista.size(); i++) {
    // cboClientes.addItem(lista.get(i).getNombre());
    // }
    // return lista;
    // }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVigente = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 220, 220));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 190, 30);
        getContentPane().add(txtCedula);
        txtCedula.setBounds(140, 90, 210, 35);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 80, 20);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(140, 130, 210, 35);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Vigente?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 170, 60, 30);
        getContentPane().add(txtVigente);
        txtVigente.setBounds(140, 170, 50, 35);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(160, 230, 100, 35);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cedula:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 100, 80, 20);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(270, 230, 80, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            String Si;
            boolean vigente;
            String cedula = txtCedula.getText();
            String nombre = txtNombre.getText();
            String textVigente = txtVigente.getText();

            if (textVigente.equals("Si")) {
                vigente = true;

            } else {
                vigente = false;
            }

            if (cedula.isEmpty() || nombre.isEmpty() || textVigente.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios");
                return;
            }

            nuevo = new Cliente(cedula, nombre, vigente);
            if (administradorArray.validarClienteExistente(listaClientes, cedula)) {
                JOptionPane.showMessageDialog(null, "Cliente ya existe");

            } else {
                listaClientes.add(nuevo);

                int input = JOptionPane.showConfirmDialog(null, "Cliente Agregado Correctamente", "",
                        JOptionPane.OK_CANCEL_OPTION);
                if (input == JOptionPane.OK_OPTION) {
                    btnSalirActionPerformed(null);
                    Inicio.mIArrendarActionPerformed(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al ingresar los Datos");
        }
        administradorArray.retornaInformacionCliente();
        // administradorArray.llenarCboClientes();

        txtCedula.setText("");
        txtNombre.setText("");
        txtVigente.setText("");

    }// GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Inicio.mIArrendarActionPerformed(null);
    }// GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVigente;
    // End of variables declaration//GEN-END:variables

}
