/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     *
     * @throws java.io.IOException
     */
    public Inicio() throws IOException {
        initComponents();

        this.setSize(new Dimension(900, 600));
        this.setMinimumSize(new Dimension(200, 200));
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Arriendo de Vehiculos en cuotas");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        escritorio = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mItemVehiculos = new javax.swing.JMenuItem();
        mItemClientes = new javax.swing.JMenuItem();
        mnuTaller = new javax.swing.JMenu();
        mIArrendar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        escritorio.setBackground(new java.awt.Color(220, 220, 220));
        escritorio.setDesktopManager(null);

        // jLabel4.setText("¡¡BIENVENIDO AL SISTEMA!!");
        // escritorio.add(jLabel4);
        // jLabel4.setBounds(170, 80, 170, 16);

        getContentPane().add(escritorio);
        escritorio.setBounds(0, 0, 1160, 500);

        mnuInicio.setMnemonic('f');
        mnuInicio.setText("INICIO");

        mItemVehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mItemVehiculos.setMnemonic('a');
        mItemVehiculos.setText("Vehiculos");
        mItemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemVehiculosActionPerformed(evt);
            }
        });
        mnuInicio.add(mItemVehiculos);

        mItemClientes.setText("Clientes");
        mItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemClientesActionPerformed(evt);
            }
        });
        mnuInicio.add(mItemClientes);

        menuBar.add(mnuInicio);

        mnuTaller.setMnemonic('h');
        mnuTaller.setText("ARRENDAR");

        mIArrendar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mIArrendar.setText("Arrendar");
        mIArrendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIArrendarActionPerformed(evt);
            }
        });
        mnuTaller.add(mIArrendar);

        menuBar.add(mnuTaller);

        mnuSalir.setText("SALIR");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        menuBar.add(mnuSalir);

        setJMenuBar(menuBar);

        // mIArrendarActionPerformed(null);
        mItemClientesActionPerformed(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_mnuSalirMouseClicked
        this.dispose();
    }// GEN-LAST:event_mnuSalirMouseClicked

    private void mItemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mItemVehiculosActionPerformed
        // TODO add your handling code here:
        IngresoVehiculo form = new IngresoVehiculo();
        escritorio.add(form);
        try {
            form.setMaximum(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
    }// GEN-LAST:event_mItemVehiculosActionPerformed

    private void mItemClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mItemClientesActionPerformed
        // TODO add your handling code here:
        IngresoCliente form = new IngresoCliente();
        escritorio.add(form);
        try {
            form.setMaximum(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);
    }// GEN-LAST:event_mItemClientesActionPerformed

    public static void mIArrendarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mIArrendarActionPerformed
        InicioArriendoCuota form = new InicioArriendoCuota();
        escritorio.add(form);
        try {
            form.setMaximum(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.toFront();
        form.setVisible(true);

    }// GEN-LAST:event_mIArrendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inicio().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem mIArrendar;
    private javax.swing.JMenuItem mItemClientes;
    private javax.swing.JMenuItem mItemVehiculos;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuTaller;
    // End of variables declaration//GEN-END:variables
}
