
package Presentacion;

import java.awt.Dimension;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

import Datos.AdministradorArrays;
import Logica.Arriendo;
import Logica.Cliente;
import Logica.CuotaArriendo;

/**
 *
 * @author jimmy
 */
public class PagarCuota extends javax.swing.JInternalFrame {

    AdministradorArrays administradorArray;
    private Cliente clienteEncontrado;
    static ArrayList<Cliente> listaClientes;
    private Arriendo arriendoSeleccionado;
    private ArrayList<Arriendo> arriendosCliente;
    private int numArriendoSeleccionado;
    private ArrayList<CuotaArriendo> listaCuotas;
    private ArrayList<CuotaArriendo> cuotasAPagar = new ArrayList<CuotaArriendo>();

    /**
     * Creates new form pagarCuota
     */
    public PagarCuota() {
        initComponents();

        administradorArray = new AdministradorArrays();
        administradorArray.crearArrayList();

        listaClientes = Cliente.getClientes();
        administradorArray.llenarCboClientes(PagarCuota.jComboBox1);

        this.setSize(new Dimension(850, 450));
        this.setMinimumSize(new Dimension(200, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnMostrarArriendo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaListado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextPane.setContentType("text/html");
        jTextPane.setEditable(false);
        jScrollPane2.setViewportView(jTextPane);

        jTextPane.addHyperlinkListener(new HyperlinkListener() {
            @Override
            public void hyperlinkUpdate(HyperlinkEvent evt) {
                jTextPaneActionPerformed(evt);
            }
        });

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(6, 149, 210, 190);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Seleccione Cliente" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 60, 240, 30);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione Arriendo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 170, 40);

        btnMostrarArriendo.setText("Mostrar Arriendo");
        btnMostrarArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarArriendoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarArriendo);
        btnMostrarArriendo.setBounds(230, 210, 160, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ARRIENDOS CON CUOTAS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 20, 260, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PAGOS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 80, 150, 30);

        jLabel7.setText("Numero ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 110, 70, 30);

        jLabel8.setText("Valor");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(550, 110, 60, 30);

        jLabel5.setText("Pagada?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 110, 70, 30);

        jtaListado.setColumns(20);
        jtaListado.setRows(5);
        jtaListado.setFont(jtaListado.getFont().deriveFont(13f));
        jScrollPane1.setViewportView(jtaListado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 140, 260, 170);

        jButton1.setText("Realizar Pago");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 320, 140, 35);

        jCheckBox1.setText("");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckboxActionPerformed(evt, 0);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(420, 140, 110, 20);

        jCheckBox2.setText("");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckboxActionPerformed(evt, 1);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(420, 160, 110, 20);

        jCheckBox3.setText("");
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckboxActionPerformed(evt, 2);
            }
        });
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(420, 180, 110, 20);

        jCheckBox4.setText("");
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckboxActionPerformed(evt, 3);
            }
        });
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(420, 200, 110, 20);

        jCheckBox5.setText("");
        jCheckBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckboxActionPerformed(evt, 4);
            }
        });
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(420, 220, 110, 20);

        jCheckBox6.setText("");
        jCheckBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckboxActionPerformed(evt, 5);
            }
        });
        getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(420, 240, 110, 20);

        jCheckBox7.setText("");
        jCheckBox7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckboxActionPerformed(evt, 6);
            }
        });
        getContentPane().add(jCheckBox7);
        jCheckBox7.setBounds(420, 260, 110, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String clienteSeleccionado = jComboBox1.getSelectedItem().toString();
        clienteEncontrado = Cliente.getCliente(clienteSeleccionado);

        arriendosCliente = Arriendo.getArriendosPorCliente(clienteEncontrado);

        String htmlArriendo = new String();
        for (int i = 0; i < arriendosCliente.size(); i++) {
            String patente = arriendosCliente.get(i).getVehiculo().getPatente();
            int numArriendo = arriendosCliente.get(i).getNumArriendo();
            htmlArriendo = htmlArriendo + "<a href=\"" + numArriendo + "\">" + patente
                    + "</a><br>";
        }

        jTextPane.setText(htmlArriendo);

    }// GEN-LAST:event_jButton1ActionPerformed

    private void btnMostrarArriendoActionPerformed(java.awt.event.ActionEvent evt) {
        Arriendo arriendoSeleccionado = arriendosCliente.get(numArriendoSeleccionado);
        listaCuotas = arriendoSeleccionado.getCuotasArriendo();

        jtaListado.setText("");

        for (int i = 0; i < listaCuotas.size(); i++) {
            int nroCuota = listaCuotas.get(i).getNumCuota();
            double montoCuota = listaCuotas.get(i).getValorCuota();
            Boolean estadoCuota = listaCuotas.get(i).getPagada();
            jtaListado.append("  " + nroCuota + "\t" + montoCuota
                    + "\t  " + estadoCuota + "\n");
        }
    }

    private void jTextPaneActionPerformed(HyperlinkEvent evt) {
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            numArriendoSeleccionado = Integer.parseInt(evt.getDescription());
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < cuotasAPagar.size(); i++) {
            cuotasAPagar.get(i).setPagada(true);
        }

        int input = JOptionPane.showConfirmDialog(null, "Las cuotas seleccionadas fueron pagadas exitosamente", "",
                JOptionPane.OK_CANCEL_OPTION);
        if (input == JOptionPane.OK_OPTION) {
            btnMostrarArriendoActionPerformed(null);
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    private void jCheckboxActionPerformed(java.awt.event.ItemEvent evt, int checkbox) {
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            cuotasAPagar.add(listaCuotas.get(checkbox));
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            cuotasAPagar.remove(listaCuotas.get(checkbox));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarCuota.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagarCuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton btnMostrarArriendo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane;
    private javax.swing.JTextArea jtaListado;
    // End of variables declaration//GEN-END:variables
}
